# Generated by Django 4.2.29 on 2026-03-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_heading_post_alter_postanalytics_post_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='postview',
            constraint=models.UniqueConstraint(fields=('post', 'ip_address'), name='unique_post_ip_view'),
        ),
    ]
